### ISSUE TITLE
Small doubt in the rot26 writeup

### ISSUE THREAD

**Issue by wr47h** [pwnsticciotti/writeups#1]
Hi!

I enjoyed going through your writeups for the Redpwn CTF. I had one doubt and I would be really glad if you could explain it to me.
In the rot26 writeup, you have written
```
exploit += '%34607x' #print enough character to reach shell[4:]
exploit += '%7$n' #write number of character printed in first address
exploit += '%32973x' #print enough character to reach shell[0:4]
exploit += '%8$n' #write number of character printed in first address
```
How did you come up with the numbers 34607 and 32973 and what is is the significance of them in the exploit. I couldn't exactly understand it from the comments.

Thank you!

**Comment by drw0if** [comment]
Firstly: thanks for the comment.

Whenever you use a string format exploit you use **%n** to write the number of character printed up to now in a variable passed to printf, more information [here](https://www.geeksforgeeks.org/g-fact-31/) (in our case we refer explicitly to the seventh variable because of the **7$** specifier) so we need to print a certain number of characters to reach the exact number to write in the address passed as first element of the exploit. You need to calculate it via trial and error since you don't know exactly how many character will be printed by the program in first place. The second number is calculated to overflow the higher part of the address since we are deciding to overwrite the got entry in two steps.
[Here](https://www.youtube.com/watch?v=t1LH9D5cuK4) an amazing video about the whole argument.

**Comment by wr47h** [comment]
Thank you so much for the explanation. I totally got it now. Thanks for the video reference as well.
